<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name=""
    nsURI="http://" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="CasaRural">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiene" upperBound="-1"
        eType="#//Dormitorio" eOpposite="#//Dormitorio/posee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dormitorio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="posee" upperBound="-1"
        eType="#//CasaRural" eOpposite="#//CasaRural/tiene"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cocina"/>
  <eClassifiers xsi:type="ecore:EClass" name="OfertaHabitacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reserva"/>
  <eClassifiers xsi:type="ecore:EClass" name="OfertaAlojamiento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Propietario"/>
</ecore:EPackage>
